name: Run TTD Telegram Bot Every 2 Hours

on:
  schedule:
    - cron: '0 */2 * * *'  # # Every 2 hours(IST)
  workflow_dispatch:       # Manual trigger option

jobs:
  run-ttd-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Using a stable version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TTD_URL: ${{ secrets.TTD_URL }}
        run: |
          python main.py
